### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@mfeurer I tried upgrading the package to the new version but the tests are failing with a path error when importing the package: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=302339&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

From what I can see in the code, you don't necessarily need this file so would it be possible to include this case in the exception, or do you maybe have a different idea how to fix this?

Line: https://github.com/openml/openml-python/blob/e336ab35ef2160ca0885d78eef59cd8d272051ee/openml/config.py#L205-L212

**Comment by mfeurer** [comment]
> From what I can see in the code, you don't necessarily need this file so would it be possible to include this case in the exception, or do you maybe have a different idea how to fix this?

I think using `os.makedirs(config_dir, exists=True)` would solve the issue. Would this be easy for you to test? If yes I could then add this to the next (minor) release.

**Comment by BastianZim** [comment]
> Would this be easy for you to test?

Yes, I'll just create a patch and test that. Will try that later.

**Comment by BastianZim** [comment]
Same problem occurs in https://github.com/openml/openml-python/blob/e336ab35ef2160ca0885d78eef59cd8d272051ee/openml/config.py#L238

Will try to the patch there as well.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@mfeurer I had to patch it in two places but seems to be working now. Can you just quickly confirm that the second patch is not breaking anything internally? Otherwise, this should be good to go.

**Comment by mfeurer** [comment]
It should not break anything. I just created a PR to fix this upstream as other projects are also hit by this error: https://github.com/openml/openml-python/pull/1053

**Comment by BastianZim** [comment]
Ok perfect, thanks for the feedback. Once your PR is merged I'll also merge this to keep the versions in sync and remove the patches again once a new release is available.

**Pull request merged**
